### ISSUE TITLE
Correct spelling

### ISSUE THREAD

**Issue by harshita0802goswami** [SahityaRoy/E-Learning-freesite#13]
Correcting spelling mistakes in the website

**Comment by SahityaRoy** [comment]
Yeah it would be helpful to correct the spellings 🤣

**Comment by harshita0802goswami** [comment]
Pls assign this issue to me

**Comment by harshita0802goswami** [comment]
Pls assign this issue to me, i want to add PR

**Comment by SahityaRoy** [comment]
PR merged @harshita0802goswami

**Comment by RakeshCharpe** [comment]
Is this issue is open if yes so i like to work on this issue under DCP'21
