### ISSUE TITLE
Modify Footer

### ISSUE THREAD

**Issue by Swastik1710** [SahityaRoy/E-Learning-freesite#21]
As of now, the footer design is minimal and quite simple. It requires social media icons and some other modifications to make it look better. I can make it look much better and attractive.

**Comment by Swastik1710** [comment]
Please assign this issue to me so that I can start working.

**Comment by SahityaRoy** [comment]
> Please assign this issue to me so that I can start working.

yes please work on it @Swastik1710  assigned to u

**Comment by SahityaRoy** [comment]
Can share your linkedin or twitter profile @Swastik1710

**Comment by Swastik1710** [comment]
Yeah sure.
Here's my LinkedIn 
https://www.linkedin.com/in/swastik-raj-singh-80ba881b8
