### ISSUE TITLE
Adding Code of Conduct file

### ISSUE THREAD

**Issue by aakankshabhende** [SahityaRoy/E-Learning-freesite#27]
Creating a Code of Conduct which everyone must abide by and mentioning the Scope of this Code of Conduct.

**Comment by swathi-469** [comment]
I would like to work on this issue please assign this to me .

**Comment by SahityaRoy** [comment]
> Creating a Code of Conduct which everyone must abide by and mentioning the Scope of this Code of Conduct.

Plz start working on it
