### ISSUE TITLE
Ripple Effect On Clicking Button

### ISSUE THREAD

**Issue by RakeshCharpe** [SahityaRoy/E-Learning-freesite#29]
I want to add ripple effect on button so it gives better looks to this site and overall it enhance the interface of the site.

**Comment by harshita9621** [comment]
Can I work on this issue

**Comment by SahityaRoy** [comment]
> I want to add ripple effect on button so it gives better looks to this site and overall it enhance the interface of the site.

@RakeshCharpe  Please go for it assigned  to you.
