### ISSUE TITLE
adding more courses

### ISSUE THREAD

**Issue by Sayyam19** [SahityaRoy/E-Learning-freesite#50]
it is just limited to 3 courses, we need to add minimum of 9 more courses of python,html,css,javasript,reactjs,angular,django,etc.
please assign this issue to me.

**Comment by SahityaRoy** [comment]
@Sayyam19  please continue with this issue

**Comment by Sayyam19** [comment]
i have completed work on issue assigned to me and also i did the pull request , please review and merge
