### ISSUE TITLE
Problem with go to top button 

### ISSUE THREAD

**Issue by shreyshreyansh** [SahityaRoy/E-Learning-freesite#56]
![Screenshot 2021-07-23 105231](https://user-images.githubusercontent.com/53744971/126740506-b5edeb08-6eb1-4ddf-b40a-61ae20c3d151.png)

**Comment by suubh** [comment]
It works perfectly fine . The green circle is for top and the white one is to switch between dark and light mode . Its cool .

**Comment by SahityaRoy** [comment]
yes i want to contribute
