### ISSUE TITLE
Dark mode button and top view button collab each other

### ISSUE THREAD

**Issue by SahityaRoy** [SahityaRoy/E-Learning-freesite#62]
**Describe the bug**
IN THE RIGHT SECTION OF THE WEBSITE IN BUTTOM YOU CAN SEE DARK MODE AND TOP ARROW OVERLAP EACH OTHER SO PLEASE FIXED THSI ISSUE .

**Expected behavior**

**Screenshots**
![29 09 2021_10 21 30_REC](https://user-images.githubusercontent.com/72821604/135205460-221ba034-617c-4466-a58c-2783ccd875e2.png)

**Comment by VibhorJaiswal** [comment]
I would like fix it.

**Comment by nishith-p-shetty** [comment]
I have fixed it. reply me please
![1](https://user-images.githubusercontent.com/69454628/135249406-f828e294-4f81-42e5-a594-a617868a8900.png)
![2](https://user-images.githubusercontent.com/69454628/135249413-1f71cd30-57dc-4ed2-89d9-8ff0b9d75b5b.png)

**Comment by SahityaRoy** [comment]
> I have fixed it. reply me please ![1](https://user-images.githubusercontent.com/69454628/135249406-f828e294-4f81-42e5-a594-a617868a8900.png) ![2](https://user-images.githubusercontent.com/69454628/135249413-1f71cd30-57dc-4ed2-89d9-8ff0b9d75b5b.png)

That's great but i suggest u to point this on top of the website in nav bar

**Comment by nishith-p-shetty** [comment]
ok working on it.

**Comment by nishith-p-shetty** [comment]
but the best place for those buttons are bottom.....?

**Comment by nishith-p-shetty** [comment]
Moved the buttons to the top. Shall i make a pull request...?
![1f](https://user-images.githubusercontent.com/69454628/135260904-6353a121-7660-42a8-a617-7f1973034f94.png)
![2f](https://user-images.githubusercontent.com/69454628/135260912-ba05d236-50b3-41b5-8b79-6dd5c030b0c0.png)

**Comment by nishith-p-shetty** [comment]
Shall i create a pull request....???

**Comment by nishith-p-shetty** [comment]
and also assign me.....

**Comment by SahityaRoy** [comment]
yes

**Comment by SahityaRoy** [comment]
Thank You For Your Contribution
