### ISSUE TITLE
Want to add Scroll to Top button

### ISSUE THREAD

**Issue by aakankshabhende** [SahityaRoy/E-Learning-freesite#8]
Will allow users to easily scroll back to top of the web page when clicked on the button.

**Comment by SahityaRoy** [comment]
Yeah you can add in bottom section. @aakankshabhende

**Comment by aakankshabhende** [comment]
Please assign me this issue @SahityaRoy

**Comment by SahityaRoy** [comment]
Yeah please continue with this issue

**Comment by SahityaRoy** [comment]
assign this issue to @aakankshabhende

**Comment by SahityaRoy** [comment]
Thanks for your info can you please share your LinkedIn profile link so that we can mention your name on website ?? @aakankshabhende

**Comment by aakankshabhende** [comment]
Yeah sure
[https://www.linkedin.com/in/aakanksha-bhende/](url)

**Comment by SahityaRoy** [comment]
thanks @aakankshabhende

**Comment by SahityaRoy** [comment]
@aakankshabhende  your profile is updated in contributor section

**Comment by aakankshabhende** [comment]
Thanks @SahityaRoy

**Comment by SahityaRoy** [comment]
Issue closed
