### ISSUE TITLE
Improve the colors in the dark mode.

### ISSUE THREAD

**Issue by khushimarothi** [SahityaRoy/E-Learning-freesite#82]
**Describe the bug**
Some of the text get blend with the background when viewed on the dark mode.

**Expected behavior**
I will improve the colors where ever required so that they don't get blended when the mode is changed.

**Comment by khushimarothi** [comment]
@SahityaRoy  please assign.

**Comment by Aatmaj-Zephyr** [comment]
@SahityaRoy Fixed in the pull request #83
