### ISSUE TITLE
Adding more online courses to the webpage

### ISSUE THREAD

**Issue by smilewithkhushi** [SahityaRoy/E-Learning-freesite#93]
**Is your feature request related to a problem? Please describe.**
Need to update the website as per the latest languages/technologies which are being used!

**Describe the solution you'd like**
I would like to add atleast three video resources for Flutter, PHP and NestJS in the section below

<img width="960" alt="Screenshot (926)" src="https://user-images.githubusercontent.com/102166679/193758072-9f3fc097-0d31-470f-8b7f-11e41222e8d1.png">

**Comment by Pranit-02** [comment]
I would like to work on this issue and also there are a lot of unnecessary comments in the index.html file need to maintain that as well !!

**Comment by shrutimeg** [comment]
I want resolve this  issue assign me this issue

**Comment by shrutimeg** [comment]
I want resolve this issue please assign me this issue
